version: '3.7'

services:

  my-app:
    build: .
    container_name: my-app
    depends_on:
      - my-app-db
    environment:
      - DEBUG=True
      - FLASK_APP=run.py
    ports:
      - 5000:5000
    restart: always
    volumes:
      - '${PWD}:/app/my-app'

  my-app-db:
    container_name: my-app-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    image: postgres:11-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
